AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DC Permit Navigator - AI chatbot for DC permits

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    MemorySize: 512

Parameters:
  BudgetEmail:
    Type: String
    Description: Email address for budget alerts
    Default: ''

Resources:
  # S3 bucket for static site + FAISS index
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'dc-permit-navigator-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # CloudFront Origin Access Control
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub 'dc-permit-navigator-oac-${AWS::AccountId}'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront distribution
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt SiteBucket.RegionalDomainName
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
          Compress: true
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html

  # S3 bucket policy - CloudFront OAC access
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontOAC
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub '${SiteBucket.Arn}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}'

  # Lambda function for RAG queries
  QueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dc-permit-navigator-query
      CodeUri: lambda/
      Handler: handler.lambda_handler
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          BUCKET_NAME: !Ref SiteBucket
          INDEX_KEY: data/embeddings/permits.index
          CHUNKS_KEY: data/embeddings/chunks.json
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref SiteBucket
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource:
                - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.titan-embed-text-v2:0'
                - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-haiku-20240307-v1:0'
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'
          AllowMethods:
            - POST
            - OPTIONS
          AllowHeaders:
            - Content-Type

  # Budget alarm at $5
  Budget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: dc-permit-navigator-budget
        BudgetLimit:
          Amount: 5
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 80
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref BudgetEmail

Outputs:
  SiteBucketName:
    Description: S3 bucket name
    Value: !Ref SiteBucket

  CloudFrontUrl:
    Description: CloudFront distribution URL
    Value: !Sub 'https://${Distribution.DomainName}'

  QueryFunctionUrl:
    Description: Lambda Function URL for RAG queries
    Value: !GetAtt QueryFunctionUrl.FunctionUrl

  DistributionId:
    Description: CloudFront distribution ID
    Value: !Ref Distribution
